version: '3.9'

services:
  osubot:
    image: ghcr.io/energostalin/osubot:latest
    build:
      context: .
      cache_from:
        - ghcr.io/energostalin/osubot:latest
      tags:
        - ghcr.io/energostalin/osubot:${RELEASE_VERSION-0}
        - ghcr.io/energostalin/osubot:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    volumes:
      - ./db:/db
    labels:
      # watchtower
      com.centurylinklabs.watchtower.enable: true